version: "3"

services:
  api:
    image: django-with-strawberry-graphql/api:${VERSION}
    command: --reload
    tty: true
    stdin_open: true
    ports:
      - 8000:8000
    volumes:
      - ./src:/code/src
